### ISSUE TITLE
Running cryosieve on cryosparc particles

### ISSUE THREAD

**Issue by msleutel** [mxhulab/cryosieve#18]
--EDIT--

Ignore my request, I now realize this should be feasible using PyEM

---

Dear all,

this look very interesting, and I would be keen to try this but I'm currently working with cryosparc. Would there be a workaround option to generate the required input files starting from the particles generated by cryosparc ?

Best,

Mike

**Comment by mxhulab** [comment]
Of course.

CryoSPARC used .cs file instead of .star file. You can use the [csparc2star.py](https://github.com/asarnow/pyem/blob/master/csparc2star.py) script to convert a .cs file to .star file.

Typically, a CryoSPARC job require a job export and then convert its .cs file to .star file, to do further processing in RELION.

I hope this message will find you well and help you.

**Comment by dzyla** [comment]
Hi,

I would like to revisit this question. Using cssparc2star to transfer particles from CryoSPARC to RELION for reconstruction, only to then return to CryoSPARC, is highly suboptimal. Could you provide a pipeline that operates entirely within CryoSPARC without needing to export particle data to a STAR file? This could address several other issues such as particle image renaming, locations, angle handling, etc.

Thanks!
Dawid

**Comment by zerinf** [comment]
Hello Dzyla, to clarify, at present, we are unable to offer a complete pipeline solely within cryoSPARC. This limitation arises from the fact that the reconstruction process in cryoSPARC appears to apply specific filters which is not open to us. The reconstruction operator plays a crucial role in computing CryoSieve's score function. We are considering the development of a custom reconstruction method tailored to our requirements in the future.
